services:
  db:
    image: bitnami/postgresql:latest
    restart: always
    environment:
      POSTGRESQL_DATABASE: ${DB_NAME}
      POSTGRESQL_USERNAME: ${DB_USER}
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    ports:
      - ${DB_PORT}:5432
volumes:
  postgres_data:
