# Generated by Django 5.0.7 on 2024-08-21 04:30

from django.db import migrations

def change_archived_tasks(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    Task.objects.filter(status = 'ARCHIVED').update(status = 'DONE')

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(change_archived_tasks),
    ]
